# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'ios-storable-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-storable-demo
  pod 'OrkaStorable', path: '../'
  pod 'OrkaPreviewData'

  target 'ios-storable-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-storable-demoUITests' do
    # Pods for testing
  end

end
